### ISSUE TITLE
Windows Install Issue

### ISSUE THREAD

**Issue by andyfedak** [jedypod/nuke-config#2]
Hey Jed,

Running into an issue on install on Windows.  I'm just replacing my .nuke folder with yours, but it seems that something in the python is adding extra spaces.  I'm looking through the python code, but having trouble finding exactly where the spaces are coming from.  

Could you take a look?

Thanks for sharing and your wonderful video on creation a Pano!
-Andy

<img width="850" alt="Screen Shot 2021-07-02 at 11 08 57 AM" src="https://user-images.githubusercontent.com/40920418/124313878-5d91ab80-db26-11eb-9b5c-346ee74a2423.png">

**Comment by jedypod** [comment]
Hey Andy!
Thanks for opening this issue... I'm aware of it, I just haven't gotten around to fixing it yet. Maybe this will motivate me!

It's coming from `tools/python/nuketools/custom_toolsets.py` ... something in that code is not properly escaping backslash characters in windows paths. It's based on Vitaly Musatov's Shared Toolsets: https://github.com/greenvfx/toolsets ... I am planning on rewriting this and massively simplifying it. 

As a workaround for now, you could delete that python file, and rename the `toolsets` directory to `ToolSets` - this will just use the default Nuke toolsets system instead.

Hope that helps, and I'll post here again when I get around to properly solving this.

**Comment by andyfedak** [comment]
Thanks for the tip Jed, most appreciated:)
Cheers,
-a

**Comment by jedypod** [comment]
I finally got around to moving toolsets to ToolSets and removing the custom_toolsets module. 

I will write a better replacement that is more customizable one of these days, but now at least life is not broken by default on windows... Will close this issue.

Thanks again for reporting this @andyfedak
