### ISSUE TITLE
Find Replace page missing

### ISSUE THREAD

**Issue by Njordy** [jedypod/nuke-config#3]
Hi. 
There is no .md file for "Find Replace" in Docs, and the link goes to 404 page.

**Comment by jedypod** [comment]
Thanks for the heads up! Yeah I never got around to documenting this tool... I will get to this one of these days, and now that you've reminded me maybe it will be sooner :)

**Comment by jedypod** [comment]
[first effort at documentation](https://github.com/jedypod/nuke-config/blob/master/doc/find_replace.md) for the find/replace tool!

Hope it helps :)
